### ISSUE TITLE
Добавить вишню на бурбоне

### ISSUE THREAD

**Issue by gbiryukov** [danila-initiative/cocktailbook#1]
У меня такое описание сохранилось:

> Не утрамбовывая, наполни двухлитровую банку свежемороженой вишней на 3/4
Добавь сахарную пудру 4 ч. ложки
Заполни оставшийся объем бурбоном
Закрой банку крышкой и настаивай неделю
Наливка готова, когда ягоды начали всплывать

**Comment by danila-initiative** [comment]
@gbiryukov, описанный рецепт тоже имеет место быть =)    
Но  оригинальный рецепт несколько отличается от описанного выше)  
https://github.com/danila-initiative/cocktailbook/blob/main/Cherry.md
